### ISSUE TITLE
remove all black/all white clovers from field

### ISSUE THREAD

**Issue by okwme** [clovers-network/clovers-dapp#155]

**Comment by okwme** [comment]
they've both been registered already , gives users false hope to stumble upon them

**Comment by evvvritt** [comment]
how might i detect that from the reversi object?
(white won:)
![image](https://user-images.githubusercontent.com/6071219/46487703-f9205100-c800-11e8-8574-0702bd8958da.png)

**Comment by okwme** [comment]
`(this.clover.rowBoard.filter(row => row.filter( tile => tile ===
this.clover.WHITE).length === 8 ) ).length === 8) ||
(this.clover.rowBoard.filter(row => row.filter( tile => tile ===
this.clover.BLACK).length === 8 ) ).length === 8)`

**Comment by okwme** [comment]
```
(this.clover.rowBoard.filter(row => row.filter( tile => tile === this.clover.WHITE).length === 8 ) ).length === 8) || (this.clover.rowBoard.filter(row => row.filter( tile => tile === this.clover.BLACK).length === 8 ) ).length === 8)
```
