### ISSUE TITLE
Prices of clovers sold to the oracle seem incredible

### ISSUE THREAD

**Issue by imrehg** [clovers-network/clovers-dapp#166]
Prices of clovers sold to the oracle for fractions of a ♣ come back 
Not sure if this is an issue, and if it is, it's more on the presentation layer or in the actual contract.

An example is `0x555555a566696559a665a555aaa5aa55`:

![screenshot_2018-09-20_16-06-44](https://user-images.githubusercontent.com/38863/45828044-918de000-bcef-11e8-98fe-c374f8e39215.png)

This had a mining reward of 0.000243386243386243 ♣

After selling it, it shows up in the field, and the cost is 24,338,624,338,625 ♣

![screenshot_2018-09-20_16-07-51](https://user-images.githubusercontent.com/38863/45828054-93f03a00-bcef-11e8-9b2a-c4a4fe427e67.png)

I would have expected the price after the original sale maybe a few multiple of the mining rewards, not many-folds more than the available supply of ♣ at the moment.

Is this a problem then? (I'd wager some signed/unsigned interpretation problem with the number_

Other examples include:

* `0xaaaaa95aaa66a696a5a6a56aaaaa6aaa` for 24,202,127,659,575 ♣
* `0x556a555a566a59aa565a9a5aaaaaaaaa` for 349,230,769,230,770 ♣
* `0x55556aaa6a5a69a66696665669566aaa` for 410,909,090,909,092 ♣

**Comment by okwme** [comment]
Hi @imrehg 👋
I have a feeling it has to do with a missing decimal conversion on the front end 🕳
The whole app still needs a thorough bug sweep after the last big sprint
Thank you for finding this one!
🐞

**Comment by okwme** [comment]
I'm wrong about this, the price multiplier was just way too large.
should have been `10` but was `100000000000000000`
😳
fixed for future calculations, have to manually reset the ones coming up wrong
