### ISSUE TITLE
Add Albums Interface

### ISSUE THREAD

**Issue by okwme** [clovers-network/clovers-dapp#174]
Once the API is built for Albums the interface needs to be built

**Comment by evvvritt** [comment]
**V1**
Albums, Album
*todo – Add to Album, Create Album*
cc @alancwoo 

*Albums.vue*
Album row shows latest two clovers? *Most-recent-two* is probably too heavy for API, so maybe author sets two "Featured"? Or just revise to one

*Album.vue*
Figured there will be a lot added to albums over time... so went with small thumbs. 
Clicking a clover pulls up the detail

![albums](https://user-images.githubusercontent.com/6071219/46671071-16279c00-cbd4-11e8-8a9a-c9cb14d1f3da.png)
![album](https://user-images.githubusercontent.com/6071219/46671069-16279c00-cbd4-11e8-83ed-18ef459105be.png)

**Comment by okwme** [comment]
woa looks nice
worried the shapes may be too small tho, realizing how small they are on the feed page, maybe we should bump them up a bit...

**Comment by evvvritt** [comment]
Made some prototypes for review:
1. [Editing/Deleting an Album ](https://sketch.cloud/s/2ejoe/nRE0KDV/play)
2. [Adding Clover to Album](https://sketch.cloud/s/2ejoe/52j9ybp/play)

Views todo:
- Account/Albums
- Profile/Albums

(both of which can just reuse this [list view](https://sketch.cloud/s/2ejoe/nRE0KDV))
