### ISSUE TITLE
Add Comments Interface

### ISSUE THREAD

**Issue by okwme** [clovers-network/clovers-dapp#175]
blocked by building the api
but needs a layout and implementation once the api is ready

**Comment by evvvritt** [comment]
**V1**
two theme ideas (I'm thinking white)
you can play the prototype here — https://sketch.cloud/s/2ejoe
- "Comment..." row would be fixed at the bottom
- page can scroll once comment tray is opened

@alancwoo any feedback?
![buy](https://user-images.githubusercontent.com/6071219/46618413-b4a5f580-cb1f-11e8-8aef-914c8674d982.png)
![comments--white](https://user-images.githubusercontent.com/6071219/46618781-b9b77480-cb20-11e8-8ec6-f134169aab6e.png)
![comments](https://user-images.githubusercontent.com/6071219/46618414-b4a5f580-cb1f-11e8-9c7b-e908376ccbe1.png)

**Comment by okwme** [comment]
love the comment icon w the x
think i like the green bg better

**Comment by okwme** [comment]
hmm fullscreen is also very nice
def like the:
* i like the comments header
* i like the border on each comment
* i like the start of chat, altho maybe not necessary
* mixed feelings about a submit button on chat, kinda feels necessary but designs always look better without. mobile sometimes acts weird with keyboards which submit on enter and some which don't
* also like green background and simple "comment..." input

**Comment by n-kort** [comment]
Yeah the minimal input is definitely better.

Couple of things missing still:
* highlight user's own comments
* pagination. 'start of chat' makes sense in this case, to indicate that we're not loading any more comments
* option to flag or delete comments if you're either the comment owner or the Clover owner
