### ISSUE TITLE
view other Users

### ISSUE THREAD

**Issue by evvvritt** [clovers-network/clovers-dapp#176]
is there already an api endpoint for this, maybe we just recycle the Account::MyClovers view?

**Comment by okwme** [comment]
yup, should be `https://api2.clovers.network/users/:id`

**Comment by evvvritt** [comment]
Added in https://github.com/clovers-network/clovers-dapp/commit/a28de2ccb6beec767e82f25b5c3c6bffb3380193

maps user's clovers from `allClovers`, but should change in future
