### ISSUE TITLE
rethink userflow / ux

### ISSUE THREAD

**Issue by okwme** [clovers-network/clovers-dapp#194]
green everywhere? maybe each section has it's own color?
two columns on desktop? maybe just single column like phone but with larger images?
moving action buttons down the page so users don't immediately go to the field and get lost?
add something like an intro video? or hand holding on welcome screen?

**Comment by evvvritt** [comment]
I like our minimal color palette but ya need to figure out how to distinguish better. I mocked up a Card style that was thinking we could use on Feed (at least first page / first 20?).
![card list](https://user-images.githubusercontent.com/6071219/49598832-c705a980-f97f-11e8-8708-3815962e7b60.png)
I do agree Field is a dead end for new users, and adding clearer buttons to Welcome page for each section would be better.

**Comment by okwme** [comment]
oo love the card layout
maybe something like a color accent to each page beyond the green? the header for ex?
