### ISSUE TITLE
MetaMask confirmation popups often do not open

### ISSUE THREAD

**Issue by n-kort** [clovers-network/clovers-dapp#196]
Pretty much all the time

**Comment by evvvritt** [comment]
or close immediately :(

**Comment by n-kort** [comment]
Issue over at the MM extension repo: https://github.com/MetaMask/metamask-extension/issues/5814

I've just had a look and it does appear to be the `global.ethereum.enable()` call in the `approve()` action. Getting rid of the polling loop fixes the problem. @okwme do we need to do this every 5 seconds?

**Comment by okwme** [comment]
fixed in #205
