### ISSUE TITLE
Netlify: doesn't deploy master properly

### ISSUE THREAD

**Issue by evvvritt** [clovers-network/clovers-dapp#216]
clv.vue in Welcome.vue doesn't get the .clover styles from inside the component (which has the border-radius:50% rule that clips the background.)

works fine when you build + view locally:
```
$ cd dist  
$ php -S localhost:3000
```
tried clearing build cache twice to no avail - may have to try redeploying as a new site entity :(

**Comment by okwme** [comment]
@n-kort should we just move everything to the team account?

**Comment by evvvritt** [comment]
it's already under bin's tho? or at least that's the one I have access too

**Comment by okwme** [comment]
i thought we moved the dev deploy to bin and the normal one is still on,,
mine i guess?

**Comment by okwme** [comment]
fixed by removing "bundle css"
they were implementing a comment on the wrong line and a whole chunk of styles were getting removed 😱
