### ISSUE TITLE
Cannot buy clover of too high a price

### ISSUE THREAD

**Issue by Flash-Git** [clovers-network/clovers-dapp#254]
https://clovers.network/clovers/0x55555555566555a555a5566555555555

`Error: [number-to-bn] while converting number "1e+21" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported.`

**Comment by okwme** [comment]
thanks for the catch @Flash-Git !
should be good to go ahead if you still wanna buy that pricey pig 🐷
