### ISSUE TITLE
UX: Pick buy/sell confusing

### ISSUE THREAD

**Issue by alancwoo** [clovers-network/clovers-dapp#282]
![image](https://user-images.githubusercontent.com/1481890/52522944-12904880-2c8c-11e9-98b2-78b457170fb6.png)

1. Different wording between option and button (eg, Claim Reward, button says Sell), potentially switch just to confirm
2. The UI seems to indicate that 'Claim reward' is greyed out and unselectable rather than being another option (vs the buy/sell tab functionality in trade)

![image](https://user-images.githubusercontent.com/1481890/52522971-51be9980-2c8c-11e9-8c9b-d94ccfe88e34.png)

**Comment by okwme** [comment]
agreeeee let's fix this!

radio button?

**Comment by n-kort** [comment]
#314
