### ISSUE TITLE
UX unclear - renaming Clover ID

### ISSUE THREAD

**Issue by lyricalpolymath** [clovers-network/clovers-dapp#304]
![Screenshot 2019-05-26 at 12 35 27](https://user-images.githubusercontent.com/516744/58380571-f43c2780-7fb2-11e9-969c-3a7e6b9f407d.jpg)

It is unclear if the ID given by the system will be needed or useful at another time.

if it is important I would always leave it accessible somewhere
or showing both the name and the generated ID

possibly, if you empty out the name field and save it, it could give the default ID.

**Comment by n-kort** [comment]
#314
