### ISSUE TITLE
[UX][improvement] - allow users to create custom collections / shelves

### ISSUE THREAD

**Issue by lyricalpolymath** [clovers-network/clovers-dapp#312]
probably for V2

but the idea is to allow users to group different clovers, in collections / shelves
and give these collections a name
this is both to the benefit of displaying and finding the clovers they like
as it is to sell: a collection can be turned into an composable NFT to sell  all together

ie I would put this one in a collection called "eroticlovers" ;)
https://clovers.network/clovers/0xaaa9aaa6aa9aa65aa966aa9aaaa6aaaa

this allows to assign more meaning to the the clovers and gives a reason to create a collection

'Super collections' can be the set of 4 same simmetries, which the dapp should automatically propose to users
while 'user collections' can be anything the user thinks fit in a group

in V3 I think it would be interesting to add to collections also clovers you don't own but are looking for or selling a collection created by a curator with clovers owned by different users (brainstorming mode for the future ;) )

**Comment by okwme** [comment]
absolutely : )
marking relevant issues for proper bookkeeping
https://github.com/clovers-network/clovers-dapp/issues/173
https://github.com/clovers-network/clovers-dapp/issues/174

**Comment by okwme** [comment]
@evvvritt
