### ISSUE TITLE
Trade graph date parsing issue

### ISSUE THREAD

**Issue by alancwoo** [clovers-network/clovers-dapp#351]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1481890/63431439-1fea7480-c41f-11e9-9a47-012117c63620.png">

**Comment by okwme** [comment]
our Y scale is always relative to the last trades coming in too.
maybe it would be good to pick a scale so that the info stays useful?

in general the graph needs a bit of a makeover : \
