### ISSUE TITLE
Missing purchased clovers - using iOS coinbase app

### ISSUE THREAD

**Issue by HeidiGaudet** [clovers-network/clovers-dapp#360]
https://etherscan.io/tx/0x0fb19df76fcadef43c42969c86868715ed28a85dc4bc016918486b48a32e1d39

https://etherscan.io/tx/0x855b77d6c80d75a34c366ce1007784f49259158e22b4ddf253d78af40cb96d75

https://etherscan.io/tx/0x16bdb72bb5f007df59e3ad508f8d510a762ceee684531dfc2a1a121ccdf025af

https://etherscan.io/tx/0x3e7441aa1e2176c06ae025becacfc81850e71fc2ce48b717bdddd229eec7f69d

![B96DB737-95B3-43C5-ADE5-BC9453159BD0](https://user-images.githubusercontent.com/19743087/63491692-2da00880-c4b8-11e9-82ab-f30e5ee2ca8c.png)
![0380C0C9-D919-431C-84AF-C14C3B068530](https://user-images.githubusercontent.com/19743087/63491693-2da00880-c4b8-11e9-9d3e-06ee2d56d7e0.png)
![525B2FC9-E3C8-460D-A4D0-036272172768](https://user-images.githubusercontent.com/19743087/63491694-2da00880-c4b8-11e9-99a5-5696c032181b.png)
![7BD0C2DB-73F6-4E09-B342-0B135AE47FFE](https://user-images.githubusercontent.com/19743087/63491695-2da00880-c4b8-11e9-9f53-85bb29373fb9.png)
![3E4EF8CB-D369-4C1D-A8DB-1F06BE777A49](https://user-images.githubusercontent.com/19743087/63491696-2e389f00-c4b8-11e9-9a45-c4808dcfbb9f.png)
![8EA067BA-A73D-422E-A581-9228366049D9](https://user-images.githubusercontent.com/19743087/63491697-2e389f00-c4b8-11e9-8823-e59fd3259c15.png)

**Comment by n-kort** [comment]
@HeidiGaudet the verification process is backed up because of gas fees. Also events have been missed since yesterday :)

This'll be fixed soon, your registrations will have worked and we just need to get the info into the DB.

**Comment by okwme** [comment]
Hey @HeidiGaudet sorry for not following up on this sooner! I'd hoped that nics was right and all your clovers would show up after the back-log got figured out. IT looks like all but one of your clovers came through. After looking at your tx's it seems the last tx got dropped, maybe you were able to cancel it through your wallet? I went in and found the clover key and re-registered it myself and sent it over to you. I think it just so happens to be the nicest looking one although that California Clover is a close runner up

p.s. don't forget to update your username!

![image](https://user-images.githubusercontent.com/964052/64443403-17a66080-d0d2-11e9-8edd-b13cb8cb29e0.png)
