### ISSUE TITLE
suggestions from discord

### ISSUE THREAD

**Issue by okwme** [clovers-network/clovers-dapp#361]
left/right buttons on the modal when you click one in your basket, so we don't have to click outside to close the modal and then click on another one.
Keep the user signed in and their pig choice, when they refresh the page.

**Comment by lazyarmadillo** [comment]
Would be nice if you could close modals using Esc key

**Comment by evvvritt** [comment]
Added:
- [x] left/right keys on Keep modal
- [x] ESC closes modals
