### ISSUE TITLE
Filter Clovers by For Sale on Profile

### ISSUE THREAD

**Issue by okwme** [clovers-network/clovers-dapp#375]
Results in some clovers not for sale. Need to modify the for sale index in the db to handle the long padded numbers from BigNumber.js

**Comment by evvvritt** [comment]
we have the filter now but doesn't seem to work properly (lists some not-for-sale)... @n-kort?
<img width="903" alt="Screenshot 2020-03-10 16 07 14" src="https://user-images.githubusercontent.com/6071219/76326726-5f0fe280-62e9-11ea-8e65-c1434b275ef2.png">
https://clovers.network/users/0x84ecb387395a1be65e133c75ff9e5fcc6f756db3/?filter=forsale
