### ISSUE TITLE
keep clover - ensure login before registration

### ISSUE THREAD

**Issue by okwme** [clovers-network/clovers-dapp#416]
when buying a clover already registered by someone and youre not logged in it doesn't tell you to login first

**Comment by evvvritt** [comment]
sign-in shows on Keep in both Basket and Garden:
<img width="392" alt="Screenshot 2020-03-10 16 38 37" src="https://user-images.githubusercontent.com/6071219/76330075-ad26e500-62ed-11ea-8ad1-2bb334a75d17.png">
